### ISSUE TITLE
Allow configuration of aws_session_token through

### ISSUE THREAD

**Issue by raphamotta** [ianbelcher/eks-kubectl-action#7]
It will be useful for temporary security credentials.

https://docs.aws.amazon.com/sdkref/latest/guide/setting-global-aws_session_token.html

**Comment by ShantKeh** [comment]
@raphamotta I had a similar need. I went ahead and created a fork that relies on the `aws-actions/configure-aws-credentials` action instead of authenticating with AWS within this action. That allowed me use use the env vars it generates, including the session token/temporary security credentials for this action.  Take a look at https://github.com/ShantKeh/eks-kubectl-action and see if that might help you out also.
